- hosts: all
  become: yes
  gather_facts: false
  tasks:
  - name: desinstalar nginx
    apt: 
      name=nginx state=absent
  
  - name: nginx andando
    service: name=nginx state=stopped

  - name: Install docker packages
    remote_user: administrator
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    tags:
      - docker
  - name: Add Docker s official GPG key
    remote_user: administrator
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    tags:
      - docker
  - name: Verify that we have the key with the fingerprint
    remote_user: administrator
    apt_key:
      id: 0EBFCD88
      state: present
    tags:
      - docker
  - name: Set up the stable repository
    remote_user: administrator
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
      update_cache: yes
    tags:
      - docker
  - name: Update apt packages
    remote_user: administrator
    apt:
      update_cache: yes
    tags:
      - docker
  - name: Install docker
    remote_user: administrator
    apt:
      name: docker-ce
      state: present
      update_cache: yes
    #notify: Start docker on boot
    tags:
      - docker
#  - name: Agregar "administrator" user a "docker" group
#    remote_user: administrator
#    user:
#      name: "administrator"
#      group: "docker"
#      append: yes
#    tags:
 #     - docker
  - name: Install docker-compose
    remote_user: administrator
    get_url: 
      url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'
  - name: agregar el usuario administrator al grupo docker
    user:
      name: administrator
      group: docker
